name: Feature Request
description: Submit a feature request
type: Feature
assignees:
  - Classsic36
body:
  - type: textarea
    id: what-is-it
    attributes:
      label: What would you like to see added/changed?
      description: A clear and concise description of what you would like to see added or changed.
      placeholder: "Example: I would like a new crafting recipe to unpack Cobwebs. The recipe would be 1 Cobweb -> 5 String."
    validations:
      required: true